module.exports = {
	mode:process.env.NODE_ENV || 'development',
	entry:{
		custom:{
			import:'./entry/custom.js',
			dependOn:"react_redux_things"
		},
		mac:{
			import:'./entry/mac.js',
			dependOn:"react_redux_things"
		},
		window: {
			import:'./entry/window.js',
			dependOn:"react_redux_things"
		},
		react_redux_things:['react-dom','react','redux','react-redux']
	},
	output:{
		filename:'[name]Bundle.js',
		path:__dirname+'/dist',
		environment:{
			arrowFunction:false,
			const:false,
			destructuring:false
		}
	},
	module:{
		rules:[
			{
				test:/\.jsx?$/, 
				exclude:/node_modules/,
				use:{
					loader:'babel-loader'
				}
			}
		]
	},
	devtool:'source-map'
}
